spring:
  # spring boot ???? ?????? ??? ???? ??
  datasource:
    # ??? JDBC Connection ??? ???? JDBC URL
    url: jdbc:sqlite:db.sqlite
    # ?? ??????? ???? ?? ?? Driver? ???? ???? ????.
    driver-class-name: org.sqlite.JDBC
    # ?? ??????? ?? ???? ????? ????.
    # username: sa
    # password: password

# MyBatis ?? ??
mybatis:
  mapper-locations: "classpath:/mybatis/mappers/*.xml"
  type-aliases-package: "com.example.crud.model"
  configuration:
    map-underscore-to-camel-case: true